name: "Release"
on:
  push:
    tags:
      - 'release/[0-9]+.[0-9]+.[0-9]+'

jobs:
  macosRelease-x64:
    name: Build MacOS-x64 Binary
    runs-on: macos-latest
    env:
      PLATFORM: mac-x64
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build hevm
        run: |
          nix build .#redistributable --out-link hevmMacos
          cp ./hevmMacos/bin/hevm ./hevm-x86_64-macos
      - uses: actions/upload-artifact@v3
        with:
          name: hevm-x86_64-macos
          path: ./hevm-x86_64-macos
  macosRelease-ARM:
    name: Build MacOS-ARM64 Binary
    runs-on: macos-latest
    env:
      PLATFORM: mac-arm64
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build hevm
        run: |
          nix build .#redistributable --out-link hevmMacos
          cp ./hevmMacos/bin/hevm ./hevm-arm64-macos
      - uses: actions/upload-artifact@v3
        with:
          name: hevm-arm64-macos
          path: ./hevm-arm64-macos
          
  linuxRelease:
    name: Create Release
    needs: [macosRelease-ARM, macosRelease-x64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build hevm
        run: |
          nix build .#redistributable --out-link hevmLinux
          cp ./hevmLinux/bin/hevm ./hevm-x86_64-linux
      - name: download macos binary
        uses: actions/download-artifact@v3
        with:
          name: hevm-x86_64-macos
      - name: create github release & upload binaries
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ./hevm-x86_64-linux
            ./hevm-x86_64-macos
            ./hevm-arm64-macos
      - name: prepare hackage artifacts
        run: |
          nix-shell --command "cabal sdist --builddir=${{ runner.temp }}/packages"
          nix-shell --command "cabal haddock lib:hevm --builddir=${{ runner.temp }}/docs --haddock-for-hackage --haddock-option=--hyperlinked-source"
      - name: publish to hackage
        uses: haskell-actions/hackage-publish@v1
        with:
          hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
          packagesPath: ${{ runner.temp }}/packages/sdist
          docsPath: ${{ runner.temp }}/docs
          publish: true



